@extends('layouts.app')

@section('title', 'Stellar Synthesis Showcase (SSS)')
@section('meta_description', 'Explore a live gallery of generative 3D badges, AI-created art, and the creative pulse of the GOAT.uz community.')
@section('canonical_url', route('sss.show'))

@push('styles')
    <style>
        .sss-dark-theme {
            background-color: #111827;
            color: #d1d5db;
        }
        .sss-dark-theme main {
            background-color: #111827;
        }
        .sss-dark-theme footer,
        .sss-dark-theme nav.fixed {
            background-color: #1f2937;
            border-color: rgba(255, 255, 255, 0.1);
            box-shadow: inset 0 0.5px 0 0.5px rgba(255,255,255,0.1);
        }
        .sss-dark-theme footer a, .sss-dark-theme footer p {
            color: #9ca3af;
        }
        .sss-dark-theme nav.fixed a, .sss-dark-theme nav.fixed svg {
            color: #d1d5db;
        }
        .sss-card {
            background-color: rgba(31, 41, 55, 0.5);
            backdrop-filter: blur(12px);
            border: 1px solid rgba(255, 255, 255, 0.1);
            transition: all 0.3s ease;
        }
        .sss-card:hover {
            border-color: rgba(79, 70, 229, 0.5);
            transform: translateY(-4px);
        }
        .text-glow-indigo {
            text-shadow: 0 0 8px rgba(255, 255, 255, 0.3), 0 0 20px rgba(99, 102, 241, 0.5);
        }
    </style>

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            document.body.classList.add('sss-dark-theme');
        });
    </script>
@endpush


@section('content')
    <div class="text-center pt-4 sm:pt-8 pb-16">
        <h1 class="text-4xl sm:text-5xl font-bold text-glow-indigo tracking-tight text-white">Stellar Synthesis Showcase</h1>
        <p class="mt-4 max-w-2xl mx-auto text-lg text-gray-400">A live canvas of our community's generative art, achievements, and collective creativity.</p>
    </div>

    {{-- Section 1: The Pantheon (Spotlight on Users) --}}
    <section class="mb-20">
        <h2 class="text-2xl font-bold text-center mb-2 text-white">The Pantheon</h2>
        <p class="text-center text-gray-400 mb-8">Celebrating the architects of our community—this week's top-rated members.</p>
        <div class="grid grid-cols-3 sm:grid-cols-4 gap-4 text-center">
            @forelse($spotlightUsers as $user)
                <a href="{{ route('profile.show', $user->username) }}" class="flex flex-col items-center group space-y-2">
                    <img src="{{ $user->profile_picture ? Storage::url($user->profile_picture) : asset('images/default-pfp.png') }}" alt="{{ $user->username }}" class="w-16 h-16 sm:w-20 sm:h-20 rounded-full object-cover border-2 border-gray-700 group-hover:border-indigo-500 transition-all duration-300 group-hover:scale-110">
                    <span class="text-xs text-white font-medium truncate w-full">{{ $user->username }}</span>
                </a>
            @empty
                <p class="col-span-full text-center text-gray-500 py-4">The Pantheon awaits its first heroes.</p>
            @endforelse
        </div>
    </section>

    {{-- Section 2: The Dream Engine (AI Art Stream) --}}
    <section class="mb-20">
        <h2 class="text-2xl font-bold text-center mb-2 text-white">The Dream Engine</h2>
        <p class="text-center text-gray-400 mb-8">A real-time stream of art generated by our members and their AI muse.</p>
        <div id="ai-art-stream" class="grid grid-cols-2 sm:grid-cols-3 gap-4">
            @forelse($recentAiCreations as $creation)
                <a href="{{ route('posts.showSlug', ['id' => $creation->id, 'slug' => $creation->slug]) }}" class="sss-card rounded-lg overflow-hidden group relative aspect-square">
                    <img src="{{ $creation->image_path ? Storage::url($creation->image_path) : 'https://placehold.co/400x400/111827/4b5563?text=Art' }}" alt="AI Generated Art by {{ $creation->user->username }}" class="w-full h-full object-cover transition-transform duration-300 group-hover:scale-110" loading="lazy">
                    <div class="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 p-3 flex flex-col justify-end">
                        <p class="text-white text-sm font-bold truncate">{{ $creation->title }}</p>
                        <p class="text-gray-300 text-xs">by {{ $creation->user->username }}</p>
                    </div>
                </a>
            @empty
                <p class="col-span-full text-center text-gray-500 py-4">The Dream Engine is warming up. No creations yet.</p>
            @endforelse
        </div>
    </section>

    {{-- Section 3: The Genesis Collection (3D Badges) --}}
    <section class="mb-20">
        <h2 class="text-2xl font-bold text-center mb-2 text-white">The Genesis Collection</h2>
        <p class="text-center text-gray-400 mb-8">An interactive constellation of our community's highest honors.</p>
        <div id="badge-constellation-container" class="relative w-full h-96 sss-card rounded-xl">
            <canvas id="badge-constellation-canvas"></canvas>
            <div class="absolute inset-0 flex items-center justify-center text-gray-500 pointer-events-none">
                <p>Badge Constellation Initializing...</p>
            </div>
        </div>
    </section>

    {{-- Section 4: The Echo Chamber (Creative Extra) --}}
    <section class="mb-16">
        <h2 class="text-2xl font-bold text-center mb-2 text-white">The Echo Chamber</h2>
        <p class="text-center text-gray-400 mb-8">A living visualization of the words defining our community conversation right now.</p>
        <div id="word-constellation-container" class="relative w-full h-64 sss-card rounded-xl p-4">
            @foreach($trendingWords as $item)
                <span class="absolute text-white transition-all duration-300 hover:text-indigo-400 hover:scale-110 cursor-default"
                      style="left: {{ rand(5, 85) }}%;
                         top: {{ rand(5, 85) }}%;
                         font-size: {{ $item['size'] * 3 }}px;
                         opacity: {{ min($item['size'] / 10, 1) }};
                         font-weight: {{ $item['size'] > 9 ? '700' : '500' }};">
                {{ $item['word'] }}
            </span>
            @endforeach
        </div>
    </section>
@endsection
