name: Gitleaks Secret Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 2 * * 1"

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    name: Detect Secrets with Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        continue-on-error: true
        with:
          args: detect --source . --no-git --report-format sarif --report-path gitleaks.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
          category: gitleaks
