# SonarCloud Scan for PHP/Laravel
# This workflow is modified to import ALL existing issues from SonarCloud to GitHub Issues.
# It should be run manually using 'workflow_dispatch'.

name: SonarCloud - Import All Issues

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  workflow_dispatch:

jobs:
  import-all-sonar-issues:
    name: Import All SonarCloud Issues to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Create issues for ALL bugs, vulnerabilities, and hotspots
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_PROJECT_KEY: 'umaarov_goat-dev'
        run: |
          echo "Fetching all unresolved issues from SonarCloud..."

          # MODIFIED: Removed branch filter and 'sinceLeakPeriod=true' to get ALL issues
          API_URL="https://sonarcloud.io/api/issues/search?componentKeys=${SONAR_PROJECT_KEY}&s=FILE_LINE&resolved=false&ps=500&types=BUG,VULNERABILITY,SECURITY_HOTSPOT"

          issues=$(curl -s -u "${SONAR_TOKEN}:" "${API_URL}")
          issue_count=$(echo "$issues" | jq '.total')

          if [ "$issue_count" -eq 0 ]; then
            echo "No unresolved issues found on SonarCloud."
            exit 0
          fi

          echo "Found $issue_count total issues. This may take a while. Creating corresponding GitHub Issues..."

          echo "$issues" | jq -c '.issues[]' | while read -r issue; do
            title=$(echo "$issue" | jq -r '.message')
            component=$(echo "$issue" | jq -r '.component')
            line=$(echo "$issue" | jq -r '.line')
            issue_key=$(echo "$issue" | jq -r '.key')

            sonar_url="https://sonarcloud.io/project/issues?id=${SONAR_PROJECT_KEY}&issues=${issue_key}&open=${issue_key}"

            body="**🚨 SonarCloud Finding (Legacy)**

            - **File:** \`$component\`
            - **Line:** $line
            - **Full Report:** [View on SonarCloud]($sonar_url)"

            # Using gh cli to create the issue
            gh issue create --title "SonarCloud: $title" --body "$body" --label "bug,sonarcloud,legacy-import"
            # Adding a small sleep to avoid hitting GitHub API rate limits
            sleep 2
          done
